well_commerce_page:
    configuration:
        page:
            orm:
                factory: WellCommerce\Bundle\PageBundle\Factory\PageFactory
                repository: WellCommerce\Bundle\PageBundle\Repository\PageRepository
                mapping: "@WellCommercePageBundle/Resources/config/doctrine/Page.orm.yml"
                entity: WellCommerce\Bundle\PageBundle\Entity\Page
            api:
                exposed: true
                dataset: page.dataset.admin
                manager: page.manager
            dynamic_routing:
                entity: WellCommerce\Bundle\PageBundle\Entity\PageRoute
                generator: WellCommerce\Bundle\PageBundle\Routing\PageRouteGenerator
                defaults:
                    _controller: page.controller.front:indexAction
        page_route:
            orm:
                mapping: "@WellCommercePageBundle/Resources/config/doctrine/PageRoute.orm.yml"
                entity: WellCommerce\Bundle\PageBundle\Entity\PageRoute
        page_translation:
            orm:
                manager: false
                mapping: "@WellCommercePageBundle/Resources/config/doctrine/PageTranslation.orm.yml"
                entity: WellCommerce\Bundle\PageBundle\Entity\PageTranslation

well_commerce_locale:
    copier:
        entities:
            WellCommerce\Bundle\PageBundle\Entity\PageTranslation:
                properties:
                    - name
                    - slug
