
services:
    page.controller.admin:
        class: WellCommerce\Bundle\PageBundle\Controller\Admin\PageController
        arguments: ['@page.manager', '@page.form_builder.admin', '@page.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    page.layout_box.configurator:
        class: WellCommerce\Bundle\LayoutBundle\Configurator\PageBoxConfigurator
        tags:
            - { name: layout_box.configurator }
        arguments: [Page, page.layout_box.controller, '@translator.helper']
        calls:
            - [setContainer, ['@service_container']]

    page.form_builder.admin:
        class: WellCommerce\Bundle\PageBundle\Form\Admin\PageFormBuilder
        tags:
            - { name: form_builder }

    page.controller.front:
        class: WellCommerce\Bundle\PageBundle\Controller\Front\PageController
        arguments: ['@page.manager']
        calls:
            - [setContainer, ['@service_container']]

    page.layout_box.controller:
        class: WellCommerce\Bundle\PageBundle\Controller\Box\PageBoxController
        arguments: ['@page.manager']
        calls:
            - [setContainer, ['@service_container']]

    twig.extension.page:
        class: WellCommerce\Bundle\PageBundle\Twig\Extension\PageExtension
        tags:
            - { name: twig.extension }
        arguments: ['@page.dataset.front']

    page.storage:
        class: WellCommerce\Bundle\PageBundle\Storage\PageStorage
