# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\PageBundle\Entity\PageInterface: WellCommerce\Bundle\PageBundle\Entity\Page

well_commerce_doctrine:
    configuration:
        page:
            factory: WellCommerce\Bundle\PageBundle\Factory\PageFactory
            repository: WellCommerce\Bundle\PageBundle\Repository\PageRepository
            mapping: "@WellCommercePageBundle/Resources/config/doctrine/Page.orm.yml"
            entity: WellCommerce\Bundle\PageBundle\Entity\Page
        page_route:
            mapping: "@WellCommercePageBundle/Resources/config/doctrine/PageRoute.orm.yml"
            entity: WellCommerce\Bundle\PageBundle\Entity\PageRoute
        page_translation:
            manager: false
            mapping: "@WellCommercePageBundle/Resources/config/doctrine/PageTranslation.orm.yml"
            entity: WellCommerce\Bundle\PageBundle\Entity\PageTranslation
